services:    
  manage:
      build:
        context: ./backend
        dockerfile: DockerfileManage
      volumes:
        - type: bind
          source: ./backend
          target: /server
      environment:
        - AML_DEBUG=${AML_DEBUG}
        - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
      ports:
        - 8001:8001