# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]

# Set line length to match flake8 configuration
line-length = 120
indent-width = 4

# Assume Python 3.11
target-version = "py311"

[lint]
# Enable Pyflakes (`F`) and a subset of the pycodestyle (`E`)  codes by default.
# Unlike Flake8, Ruff doesn't enable pycodestyle warnings (`W`) or
# McCabe complexity (`C901`) by default.
select = ["E4", "E7", "E9", "F"]

# Disable a variety of commonly ignored rules.
ignore = [
    "E722", # Do not use bare 'except'
    "F722", # Syntax error identified by pyflakes
    "F821", # Undefined name
    "E501", # Line too long
    "F401", # Unused import
    "F403", # 'from module import *' used; unable to detect undefined names
    "F405", # Name may be undefined, or defined from star imports
    "F811", # Redefinition of unused name from line N
    "F841", # Local variable name is assigned to but never used
    "E201", # Whitespace after '('
    "E202", # Whitespace before ')'
    "E203", # Whitespace before ':'
    "E222", # Multiple spaces after operator
    "E225", # Missing whitespace around operator
    "E231", # Missing whitespace after ','
    "E251", # Unexpected spaces around keyword / parameter equals
    "E262", # Inline comment should start with '# '
    "E261", # At least two spaces before inline comment
    "W191", # Indentation contains tabs
    "W291", # Trailing whitespace
    "W292", # No newline at end of file
    "W293", # Blank line contains whitespace
    "W391", # Blank line at end of file
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"

# Disable auto-formatting of code examples in docstrings to match flake8 behavior.
docstring-code-format = false

# Set the line length limit used when formatting code snippets in docstrings.
docstring-code-line-length = "dynamic"
