# Generated by Django 3.2.25 on 2024-03-19 12:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20240306_1930_squashed_0004_alter_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='alt',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='href',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='rel',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='image',
            name='target',
            field=models.CharField(blank=True, choices=[('_self', 'Self'), ('_blank', 'Blank'), ('_parent', 'Parent'), ('_top', 'Top')], default=('_self', 'Self'), max_length=255),
        ),
    ]
