# Generated by Django 3.2.25 on 2024-06-05 08:50

from django.db import migrations
import image.models
import image.validators


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_remove_null_string_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=image.models.SVGAndImageField(upload_to='%Y/%m/%d/', validators=[image.validators.FileValidator(allowed_extensions=['.jpg', '.jpeg', '.png', '.gif', '.svg', '.webp'], allowed_mimetypes=['image/jpeg', 'image/png', 'image/gif', 'image/svg+xml', 'image/webp'])]),
        ),
    ]
