# Generated by Django 4.2.18 on 2025-03-25 10:20

import django.contrib.postgres.fields
from django.db import migrations, models
import image.models
import image.validators


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_allow_webp_svg_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='alt',
            field=models.CharField(blank=True, default='', help_text='Alternative text for the image.', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the image was created.'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Description of the image.'),
        ),
        migrations.AlterField(
            model_name='image',
            name='file',
            field=image.models.SVGAndImageField(help_text='Uploaded image file.', upload_to='%Y/%m/%d/', validators=[image.validators.FileValidator(allowed_extensions=['.jpg', '.jpeg', '.png', '.gif', '.svg', '.webp'], allowed_mimetypes=['image/jpeg', 'image/png', 'image/gif', 'image/svg+xml', 'image/webp'])]),
        ),
        migrations.AlterField(
            model_name='image',
            name='href',
            field=models.URLField(blank=True, default='', help_text='URL that the image links to.'),
        ),
        migrations.AlterField(
            model_name='image',
            name='rel',
            field=models.CharField(blank=True, default='', help_text='Relationship attribute for the link.', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, help_text='Tags associated with the image.', size=None),
        ),
        migrations.AlterField(
            model_name='image',
            name='target',
            field=models.CharField(blank=True, choices=[('_self', 'Self'), ('_blank', 'Blank'), ('_parent', 'Parent'), ('_top', 'Top')], default=('_self', 'Self'), help_text='Specifies where to open the linked document.', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='title',
            field=models.CharField(help_text='Title of the image.', max_length=255),
        ),
        migrations.AlterField(
            model_name='image',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the image was last updated.'),
        ),
    ]
