# Generated by Django 6.0.5 on 2026-05-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_add_image_help_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='background_color',
            field=models.CharField(blank=True, choices=[('colorBackground', 'Background color'), ('colorGrey', 'Grey color'), ('colorNegative', 'Negative color'), ('colorNeutral1', 'Neutral color 1'), ('colorNeutral2', 'Neutral color 2'), ('colorNeutral3', 'Neutral color 3'), ('colorPositive', 'Positive color'), ('colorPrimary', 'Primary color'), ('colorSecondary', 'Secondary color'), ('colorText', 'Text color')], default='', help_text='Show color from current theme (e.g. `colorPositive`) as image background', max_length=32),
        ),
    ]
