# Generated by Django 6.0.5 on 2026-05-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_add_image_help_texts'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='background_color',
            field=models.CharField(blank=True, choices=[('color_background', 'colorBackground'), ('color_grey', 'colorGrey'), ('color_negative', 'colorNegative'), ('color_neutral1', 'colorNeutral1'), ('color_neutral2', 'colorNeutral2'), ('color_neutral3', 'colorNeutral3'), ('color_positive', 'colorPositive'), ('color_primary', 'colorPrimary'), ('color_secondary', 'colorSecondary'), ('color_text', 'colorText')], default='', help_text='Show color from current theme (e.g. `colorPositive`) as image background', max_length=32),
        ),
    ]
