# Generated by Django 6.0.7 on 2026-09-01 06:49

import image.models
import image.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_image_background_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=image.models.SVGAndImageField(help_text='Uploaded image file.', upload_to=image.models.image_upload_path, validators=[image.validators.FileValidator(allowed_extensions=['.jpg', '.jpeg', '.png', '.gif', '.svg', '.webp'], allowed_mimetypes=['image/jpeg', 'image/png', 'image/gif', 'image/svg+xml', 'image/webp'])]),
        ),
    ]
