# Generated by Django 3.2.23 on 2023-12-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('css_variables', models.TextField()),
                ('additional_variables', models.TextField(blank=True)),
                ('global_css', models.TextField(blank=True)),
            ],
        ),
    ]
