# Generated by Django 3.2.24 on 2024-02-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('font_url', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.CharField(blank=True, max_length=255, null=True)),
                ('background_url', models.CharField(blank=True, max_length=255, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
