# Generated by Django 3.2.24 on 2024-02-16 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeconfig',
            name='background',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='themeconfig',
            name='font',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='themeconfig',
            name='logo',
            field=models.TextField(blank=True),
        ),
    ]
