# Generated by Django 3.2.24 on 2024-02-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_auto_20240216_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeconfig',
            name='background',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='themeconfig',
            name='font',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='themeconfig',
            name='logo',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
