# Generated by Django 3.2.24 on 2024-02-28 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_auto_20240228_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themeconfig',
            name='active',
        ),
    ]
