# Generated by Django 3.2.25 on 2024-03-19 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_remove_null_string_fields'),
        ('theme', '0003_remove_themeconfig_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themeconfig',
            name='background_url',
        ),
        migrations.RemoveField(
            model_name='themeconfig',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='themeconfig',
            name='background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme_background', to='image.image'),
        ),
        migrations.AddField(
            model_name='themeconfig',
            name='logo_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme_logo', to='image.image'),
        ),
        migrations.AlterField(
            model_name='themeconfig',
            name='body_font_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='themeconfig',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='themeconfig',
            name='heading_font_url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
