# Generated by Django 3.2.24 on 2024-02-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_auto_20240216_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themeconfig',
            name='additional_variables',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='themeconfig',
            name='background',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='themeconfig',
            name='font',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='themeconfig',
            name='global_css',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='themeconfig',
            name='logo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
