# Generated by Django 3.2.24 on 2024-02-16 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_auto_20240216_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeconfig',
            name='name',
            field=models.CharField(default='Default', max_length=255, unique=True),
        ),
    ]
