# Generated by Django 3.2.25 on 2024-03-19 15:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import theme.models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_remove_null_string_fields'),
        ('theme', '0004_alter_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.FileField(blank=True, default='', help_text='Upload a file in html or markdown format', upload_to=theme.models.footer_info_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['md', 'html'])])),
                ('logos', models.ManyToManyField(blank=True, help_text='Add references to Image objects; make sure these have sufficient contrast with the background (image).', to='image.Image')),
                ('theme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='theme.themeconfig')),
            ],
        ),
    ]
