# Generated by Django 3.2.25 on 2024-03-26 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0003_remove_null_string_fields'),
        ('theme', '0004_alter_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disclaimer', models.TextField(blank=True, default='')),
                ('privacy', models.TextField(blank=True, default='')),
                ('logos', models.ManyToManyField(blank=True, help_text='Add references to Image objects; make sure these have sufficient contrast with the background (image).', to='image.Image')),
                ('theme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='footer', to='theme.themeconfig')),
            ],
        ),
    ]
