# Generated by Django 3.2.24 on 2024-02-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0005_themeconfig_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='themeconfig',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
