# Generated by Django 3.2.25 on 2024-04-24 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0005_footerconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_score', models.BooleanField(default=False)),
                ('theme', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='header', to='theme.themeconfig')),
            ],
        ),
    ]
