# Generated by Django 4.2.14 on 2024-07-15 10:04

from django.db import migrations, models
import django.db.models.deletion


# Copy old logos to new SponsorImage model
def migrate_logos(apps, schema_editor):
    FooterConfig = apps.get_model('theme', 'FooterConfig')
    SponsorImage = apps.get_model('theme', 'SponsorImage')

    for footer in FooterConfig.objects.all():
        for index, image in enumerate(footer.logos.all()):
            SponsorImage.objects.create(
                footer_config=footer,
                image=image,
                index=index
            )


# Copy new logos back to old logos field
def reverse_migrate_logos(apps, schema_editor):
    FooterConfig = apps.get_model('theme', 'FooterConfig')
    SponsorImage = apps.get_model('theme', 'SponsorImage')

    for footer in FooterConfig.objects.all():
        footer.logos.set(SponsorImage.objects.filter(footer_config=footer)
                         .values_list('image', flat=True))


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0004_allow_webp_svg_images'),
        ('theme', '0006_headerconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('footer_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_images', to='theme.footerconfig')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.image')),
            ],
            options={
                'ordering': ['index'],
                'unique_together': {('footer_config', 'image')},
            },
        ),
        migrations.AddField(
            model_name='footerconfig',
            name='new_logos',
            field=models.ManyToManyField(blank=True, help_text='Add references to Image objects; make sure these have sufficient contrast with the background (image).', related_name='footer_configs', through='theme.SponsorImage', to='image.image'),
        ),
        migrations.RunPython(migrate_logos, reverse_migrate_logos),
        migrations.RemoveField(
            model_name='footerconfig',
            name='logos',
        ),
        migrations.RenameField(
            model_name='footerconfig',
            old_name='new_logos',
            new_name='logos',
        ),
    ]
