# Generated by Django 4.2.11 on 2024-07-08 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0006_headerconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='footerconfig',
            name='disclaimer_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='footerconfig',
            name='disclaimer_nl',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='footerconfig',
            name='disclaimer_pt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='footerconfig',
            name='disclaimer_zh_hans',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='footerconfig',
            name='privacy_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='footerconfig',
            name='privacy_nl',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='footerconfig',
            name='privacy_pt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='footerconfig',
            name='privacy_zh_hans',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='themeconfig',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='themeconfig',
            name='description_nl',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='themeconfig',
            name='description_pt',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='themeconfig',
            name='description_zh_hans',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
