# Generated by Django 3.2.18 on 2023-03-14 14:07

from django.db import migrations, models
import section.models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='filename',
            field=models.FileField(max_length=128, upload_to=section.models.audio_upload_path),
        ),
    ]
