# Generated by Django 3.2.18 on 2023-05-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='filename',
            field=models.CharField(max_length=255),
        ),
    ]
