# Generated by Django 3.2.20 on 2023-10-03 15:11

import django.core.validators
from django.db import migrations, models
import section.models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0004_update_song_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name="section",
            name="filename",
            field=models.FileField(
                max_length=255,
                upload_to=section.models._audio_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["wav", "mp3", "aiff", "flac", "ogg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="group",
            field=models.CharField(blank=True, default="0", max_length=128),
        ),
        migrations.AlterField(
            model_name="section",
            name="tag",
            field=models.CharField(blank=True, default="0", max_length=128),
        ),
    ]
