# Generated by Django 3.2.24 on 2024-02-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0006_auto_20240126_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='url_prefix',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
