# Generated by Django 3.2.24 on 2024-03-14 08:53

from django.db import migrations, models
import section.validators


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0007_playlist_url_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='url_prefix',
            field=models.CharField(
                blank=True,
                default='',
                max_length=128,
                validators=[section.validators.url_prefix_validator]),
        ),
    ]
