# Generated by Django 4.2.15 on 2024-10-18 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0008_alter_playlist_url_prefix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='code',
        ),
    ]
