#!/bin/bash

# This script is used to build the docker image and run the tests in a container
docker build -t selenium-tests .
docker run --rm -it -p 4444:4444 -p 5900:5900 -p 7900:7900 --network="host" --name selenium-tests-container -v $(pwd):/usr/src/app --entrypoint bash selenium-tests