# Generated by Django 3.2.20 on 2023-11-23 12:39

from django.db import migrations
import json


def forwards_func(apps, schema_editor):
    Session = apps.get_model('session', 'Session')
    for session in Session.objects.all():
        if session.json_data:
            for key,value in json.loads(session.json_data).items():
                session.json_temp[key] = value
                session.save()


def reverse_func(apps, schema_editor):
    Session = apps.get_model('session', 'Session')
    for session in Session.objects.all():        
        session.json_data = json.dumps(session.json_temp)
        session.save()


class Migration(migrations.Migration):

    dependencies = [('session', '0002_session_json_temp'),]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
