# Generated by Django 3.2.20 on 2023-11-26 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0004_auto_20231124_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='old_data',
        ),
    ]
