# Generated by Django 4.2.15 on 2024-10-18 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0006_rename_experiment_session_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='current_round',
        ),
    ]
