# Generated by Django 4.2.22 on 2025-12-17 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_participant_id_url'),
        ('experiment', '0071_change_phase_index_help_text'),
        ('session', '0007_remove_session_current_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='experiment.block'),
        ),
        migrations.AlterField(
            model_name='session',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='participant.participant'),
        ),
    ]
