# Generated by Django 3.2.25 on 2024-05-01 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInterfaceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminInterfaceThemeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_primary', models.CharField(blank=True, default='#79aec8', max_length=255)),
                ('color_secondary', models.CharField(blank=True, default='#417690', max_length=255)),
                ('color_accent', models.CharField(blank=True, default='#f5dd5d', max_length=255)),
                ('color_primary_fg', models.CharField(blank=True, default='#fff', max_length=255)),
                ('color_body_fg', models.CharField(blank=True, default='#333', max_length=255)),
                ('color_body_bg', models.CharField(blank=True, default='#fff', max_length=255)),
                ('color_body_quiet_color', models.CharField(blank=True, default='#666', max_length=255)),
                ('color_body_loud_color', models.CharField(blank=True, default='#000', max_length=255)),
                ('color_header_color', models.CharField(blank=True, default='#ffc', max_length=255)),
                ('color_breadcrumbs_fg', models.CharField(blank=True, default='#c4dce8', max_length=255)),
                ('color_link_fg', models.CharField(blank=True, default='#447e9b', max_length=255)),
                ('color_link_hover_color', models.CharField(blank=True, default='#036', max_length=255)),
                ('color_link_selected_fg', models.CharField(blank=True, default='#5b80b2', max_length=255)),
                ('color_hairline_color', models.CharField(blank=True, default='#e8e8e8', max_length=255)),
                ('color_border_color', models.CharField(blank=True, default='#ccc', max_length=255)),
                ('color_error_fg', models.CharField(blank=True, default='#ba2121', max_length=255)),
                ('color_message_success_bg', models.CharField(blank=True, default='#dfd', max_length=255)),
                ('color_message_warning_bg', models.CharField(blank=True, default='#ffc', max_length=255)),
                ('color_message_error_bg', models.CharField(blank=True, default='#ffefef', max_length=255)),
                ('color_darkened_bg', models.CharField(blank=True, default='#f8f8f8', max_length=255)),
                ('color_selected_bg', models.CharField(blank=True, default='#e4e4e4', max_length=255)),
                ('color_selected_row', models.CharField(blank=True, default='#ffc', max_length=255)),
                ('color_button_fg', models.CharField(blank=True, default='#fff', max_length=255)),
                ('color_button_bg', models.CharField(blank=True, default='#79aec8', max_length=255)),
                ('color_button_hover_bg', models.CharField(blank=True, default='#609ab6', max_length=255)),
                ('color_default_button_bg', models.CharField(blank=True, default='#417690', max_length=255)),
                ('color_default_button_hover_bg', models.CharField(blank=True, default='#205067', max_length=255)),
                ('color_close_button_bg', models.CharField(blank=True, default='#888', max_length=255)),
                ('color_close_button_hover_bg', models.CharField(blank=True, default='#747474', max_length=255)),
                ('color_delete_button_bg', models.CharField(blank=True, default='#ba2121', max_length=255)),
                ('color_delete_button_hover_bg', models.CharField(blank=True, default='#a41515', max_length=255)),
                ('color_default_bg', models.CharField(blank=True, default='#f8d7da', max_length=255)),
                ('color_default_fg', models.CharField(blank=True, default='#721c24', max_length=255)),
                ('color_success_bg', models.CharField(blank=True, default='#d4edda', max_length=255)),
                ('color_success_fg', models.CharField(blank=True, default='#155724', max_length=255)),
                ('color_warning_bg', models.CharField(blank=True, default='#fff3cd', max_length=255)),
                ('color_warning_fg', models.CharField(blank=True, default='#856404', max_length=255)),
                ('color_error_bg', models.CharField(blank=True, default='#f8d7da', max_length=255)),
                ('configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='admin_interface.admininterfaceconfiguration')),
            ],
        ),
    ]
