# Generated by Django 3.2.25 on 2024-04-30 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInterfaceConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='AdminInterfaceThemeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_default_bg', models.CharField(blank=True, default='#f8d7da', max_length=255)),
                ('color_default_fg', models.CharField(blank=True, default='#721c24', max_length=255)),
                ('color_success_bg', models.CharField(blank=True, default='#d4edda', max_length=255)),
                ('color_success_fg', models.CharField(blank=True, default='#155724', max_length=255)),
                ('color_warning_bg', models.CharField(blank=True, default='#fff3cd', max_length=255)),
                ('color_warning_fg', models.CharField(blank=True, default='#856404', max_length=255)),
                ('color_error_bg', models.CharField(blank=True, default='#f8d7da', max_length=255)),
                ('color_error_fg', models.CharField(blank=True, default='#721c24', max_length=255)),
                ('configuration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme', to='admin_interface.admininterfaceconfiguration')),
            ],
        ),
    ]
