#!/bin/bash

# Path to the hosts file
HOSTS_FILE="/etc/hosts"

YELLOW_BEGIN="\e[33m"
YELLOW_END="\e[0m"
GREEN_BEGIN="\e[32m"
GREEN_END="\e[0m"

# Function to remove existing hosts entries
remove_existing_hosts_entries() {
    printf $"${GREEN_BEGIN}"
    echo -e "\nRemoving existing entries for MUSCLE..."
    printf "${GREEN_END}"
    # Check if we are on macOS and adjust the sed command accordingly
    if [[ "$OSTYPE" == "darwin"* ]]; then
        sudo sed -i '' '/# MUSCLE/,/# END MUSCLE/d' "$HOSTS_FILE"
    else
        sudo sed -i '/# MUSCLE/,/# END MUSCLE/d' "$HOSTS_FILE"
    fi
}

# Function to add hosts entries
add_hosts_entries() {
    printf $"${GREEN_BEGIN}"
    echo -e "\nAdding the following entries to your hosts file:"
    printf "${GREEN_END}"
    for entry in "${HOST_ENTRIES[@]}"; do
        echo "$entry"
    done
    printf $"${YELLOW_BEGIN}"
    echo -e "\nYou may be asked for your password.\n"
    printf "${YELLOW_END}"
    for entry in "${HOST_ENTRIES[@]}"; do
        echo "$entry" | sudo tee -a "$HOSTS_FILE" > /dev/null
    done

    printf "\nDone! You can now access the MUSCLE user interface at ${GREEN_BEGIN}http://$main_domain${GREEN_END} and the admin interface at ${GREEN_BEGIN}http://$backend_domain/admin${GREEN_END}.\n"
}

# Function to get domain selection
get_domain_selection() {
    local PS3="Please choose a domain for $1: "
    local options=("$2" "$3" "other (type a custom domain yourself)")
    local domain

    select opt in "${options[@]}"; do
        case $REPLY in
            1) domain=$2; break ;;
            2) domain=$3; break ;;
            *) domain=$REPLY; break ;;
        esac
    done

    echo "$domain"
}

# Main domain selection
printf $"${YELLOW_BEGIN}"
echo -e "\n# Define main site domain (the user interface)"
printf "${YELLOW_END}"
main_domain=$(get_domain_selection "main site" "muscle.local" "localhost:3000")

printf "\nYou have chosen ${GREEN_BEGIN}$main_domain${GREEN_END} as your main site domain.\n"

# Backend domain selection
printf $"${YELLOW_BEGIN}"
echo -e "\n# Define backend domain (the admin interface)"
printf "${YELLOW_END}"
backend_domain=$(get_domain_selection "backend" "backend.muscle.local" "localhost:8000")

printf "\nYou have chosen ${GREEN_BEGIN}$backend_domain${GREEN_END} as your backend domain.\n"

# Define hosts entries
HOST_ENTRIES=(
    "# MUSCLE"
    "127.0.0.1 $main_domain"
    "127.0.0.1 $backend_domain"
    "# END MUSCLE"
)

# Backup the original hosts file
sudo cp "$HOSTS_FILE" "${HOSTS_FILE}.bak"

# Remove existing MUSCLE entries
remove_existing_hosts_entries

# Add new MUSCLE entries
add_hosts_entries