#!/bin/bash
# -----------------------------------------
composefile=docker-compose.yaml
while (($#)); do
  case "$1" in
    -p)
      echo "-p flag passed" >&2
      composefile=docker-compose-deploy.yml
      ;;
    -*)
      echo "Invalid option: $1" >&2
      exit 1
      ;;
    *)
      if [[ -n "$dump_filename" ]]; then
        echo "Error: provide only one filename." >&2
        exit 1
      fi
      dump_filename=$1
      ;;
  esac
  shift
done
CURRENT_DATE=$(date +%Y%m%d)
DUMP_FILENAME=${dump_filename:-$CURRENT_DATE}
[[ "$DUMP_FILENAME" == *.sql ]] || DUMP_FILENAME="${DUMP_FILENAME}.sql"
DUMP_PATH="/backups/$DUMP_FILENAME"
echo "Starting database dump $DUMP_FILENAME.sql from $composefile"

# Step 1: Start database container from current branch
echo "Taking down all containers and starting new PostgreSQL container"
docker compose -f $composefile down
docker compose -f $composefile up db -d

# Step 2: Wait for database container to be ready
echo "Waiting for PostgreSQL container to be ready..."
until docker exec muscle_db pg_isready; do
  sleep 1;
done;

# Step 3: Make database dump
echo "Dumping the database from current PostgreSQL container"
docker exec muscle_db sh -c "pg_dump > $DUMP_PATH"

# Step 4: Verify that the dump file exists on the host.
if ! docker exec muscle_db test -f "$DUMP_PATH"; then
  echo "Error: $DUMP_FILENAME was not created."
  exit 1
fi
echo "Dump file created on db_backup volume: $DUMP_FILENAME"