#!/bin/bash
# -----------------------------------------
composefile=docker-compose.yaml
# if -p flag is passed, run everything on the docker-compose-deploy.yml file
if getopts 'p:'; then
    composefile=docker-compose-deploy.yml
fi
# ------------------------------------------
# Step 1. Stop containers
echo "1. Stopping all containers..."
docker compose -f $composefile down
# Step 2. Start database container
echo "2. Starting database container..."
docker compose -f $composefile up db -d
# Step 3. Create dump file
echo "3. Create db-dump.sql"
docker compose run --rm  db pg_dumpall > db-dump.sql
docker compose down
echo 