#!/bin/bash

# Get the absolute path of the project root directory
PROJECT_ROOT=$(cd "$(dirname "$0")/.." && pwd)

# Build the image using the backend directory as the context
docker build --target graphviz -t muscle-db-schema-generator -f "$PROJECT_ROOT/backend/DockerfileDevelop" "$PROJECT_ROOT/backend"

# Run the container to generate the image
docker run --rm \
    -e DJANGO_SETTINGS_MODULE=aml.graphviz_settings \
    -v "$PROJECT_ROOT/backend:/server" \
    -v "$PROJECT_ROOT/backend/static:/server/static" \
    muscle-db-schema-generator
