#!/bin/bash

# Ruff allows you to lint your Python code with a variety of linters.
# This script runs the Ruff linter on the backend codebase.
# It uses the `ruff check` command to lint the codebase.
# The `--watch` flag tells Ruff to watch the codebase for changes and re-lint the codebase when changes are detected.
# The `--fix` flag tells Ruff to automatically fix any linting errors that it can.
docker compose run --rm server bash -c "ruff check $@"
