#!/bin/bash
# -----------------------------------------
composefile=docker-compose.yaml
production=0
while getopts ":p" opt; do
  case $opt in
    p)
      echo "-p flag passed" >&2
      composefile=docker-compose-deploy.yml
      production=1
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      ;;
  esac
done
echo "Starting database upgrade from $composefile"
read -p "Enter the name of the branch on which the updated postgres version can be found: " GIT_BRANCH
CURRENT_DATE=$(date +%Y%m%d)
echo $CURRENT_DATE

# Step 1: Start database container from current branch
echo "Starting PostgreSQL container from current branch"
docker compose -f $composefile down
docker compose -f $composefile up db -d

# Step 2: Make database dump
echo "Dumping the database from current PostgreSQL container"
docker exec -it muscle_db sh -c "pg_dump > /backups/$CURRENT_DATE-migration.sql"
FILECHECK=$(docker exec muscle_db ls /backups)

# Step 3: Verify that the dump file exists on the host.
if [[ ! "$FILECHECK" == *"$DATE"* ]]; then
  echo "Error: $(DATE)-migration.sql was not created."
  exit 1
fi
echo "Dump file created on db_backup volume: $CURRENT_DATE-migration.sql"

# ----------------------------------------------------------------------------
# Step 4: Stop all containers
#
echo "Stopping and removing containers..."
docker compose -f $composefile down

# ----------------------------------------------------------------------------
# Step 5: Remove the old volume so that a new one can be created.
#
echo "Removing old volume 'muscle_db_data'..."
docker volume rm muscle_db_data
if [$production]; then
  podman unshare
  rm -r ~/podman-volumes/db-data/*
  exit
fi

# ----------------------------------------------------------------------------
# Step 6: Pull the branch with the new version.
#
git pull
git checkout $GIT_BRANCH

# ----------------------------------------------------------------------------
# Step 7: Start up db service with updated Postgres version
#
docker compose -f $dockerfile up db

echo "Waiting for PostgreSQL to be ready..."
until [ "`docker exec muscle_db pg_isready `" ]; do
    sleep 1;
done;


# Run the restore using the default 'postgres' user and its default database.
echo "Running restore..."
docker exec muscle_db psql -f /backups/$(DATE)-migration.sql


# ----------------------------------------------------------------------------
# Step 8: Finally, restart your project with the updated configuration.
#
echo "Restarting the project..."
docker compose -f $dockerfile down
docker compose -f $dockerfile up -d --build

echo "Migration complete."
