# Generated by Django 6.0.5 on 2026-05-20 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Explainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(blank=True, default='', max_length=256)),
                ('instruction_en', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('instruction_nl', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('instruction_pt', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('instruction_zh_hans', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('instruction_tr', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('timer', models.IntegerField(blank=True, default=0)),
                ('number_steps', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=256)),
                ('description_en', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('description_nl', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('description_pt', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('description_zh_hans', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('description_tr', models.CharField(blank=True, default='', max_length=256, null=True)),
                ('index', models.IntegerField(blank=True, default=1)),
                ('explainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='action.explainer')),
            ],
        ),
    ]
