# Generated by Django 6.0.5 on 2026-05-20 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='explainer',
            name='identifier',
            field=models.SlugField(default='test1', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
