# Generated by Django 6.0.5 on 2026-05-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0002_explainer_identifier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['index']},
        ),
        migrations.AlterField(
            model_name='explainer',
            name='timer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
