# Generated by Django 6.0.5 on 2026-06-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0003_explainer_timer_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='explainer',
            name='instruction_de',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='description_de',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
