# Generated by Django 6.0.5 on 2026-07-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('action', '0004_add_german_language_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='explainer',
            name='instruction_ja',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='description_ja',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
    ]
