from django.utils.translation import gettext_lazy as _

ISO_LANGUAGES = {
    'ab': _('Abkhazian'),
    'aa': _('Afar'),
    'af': _('Afrikaans'),
    'ak': _('Akan'),
    'sq': _('Albanian'),
    'am': _('Amharic'),
    'ar': _('Arabic'),
    'an': _('Aragonese'),
    'hy': _('Armenian'),
    'as': _('Assamese'),
    'av': _('Avaric'),
    'ae': _('Avestan'),
    'ay': _('Aymara'),
    'az': _('Azerbaijani'),
    'bm': _('Bambara'),
    'ba': _('Bashkir'),
    'eu': _('Basque'),
    'be': _('Belarusian'),
    'bn': _('Bengali'),
    'bh': _('Bihari languages'),
    'bi': _('Bislama'),
    'nb': _('Bokmål), Norwegian; Norwegian Bokmål'),
    'bs': _('Bosnian'),
    'br': _('Breton'),
    'bg': _('Bulgarian'),
    'my': _('Burmese'),
    'ca': _('Catalan; Valencian'),
    'km': _('Central Khmer'),
    'ch': _('Chamorro'),
    'ce': _('Chechen'),
    'ny': _('Chichewa; Chewa; Nyanja'),
    'zh': _('Chinese'),
    'cu': _(
        'Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic'
    ),
    'cv': _('Chuvash'),
    'kw': _('Cornish'),
    'co': _('Corsican'),
    'cr': _('Cree'),
    'hr': _('Croatian'),
    'cs': _('Czech'),
    'da': _('Danish'),
    'dv': _('Divehi; Dhivehi; Maldivian'),
    'nl': _('Dutch; Flemish'),
    'dz': _('Dzongkha'),
    'en': _('English'),
    'eo': _('Esperanto'),
    'et': _('Estonian'),
    'ee': _('Ewe'),
    'fo': _('Faroese'),
    'fj': _('Fijian'),
    'fi': _('Finnish'),
    'fr': _('French'),
    'ff': _('Fulah'),
    'gd': _('Gaelic; Scottish Gaelic'),
    'gl': _('Galician'),
    'lg': _('Ganda'),
    'ka': _('Georgian'),
    'de': _('German'),
    'el': _('Greek), Modern (1453-)'),
    'gn': _('Guarani'),
    'gu': _('Gujarati'),
    'ht': _('Haitian; Haitian Creole'),
    'ha': _('Hausa'),
    'he': _('Hebrew'),
    'hz': _('Herero'),
    'hi': _('Hindi'),
    'ho': _('Hiri Motu'),
    'hu': _('Hungarian'),
    'is': _('Icelandic'),
    'io': _('Ido'),
    'ig': _('Igbo'),
    'id': _('Indonesian'),
    'ia': _('Interlingua (International Auxiliary Language Association)'),
    'ie': _('Interlingue; Occidental'),
    'iu': _('Inuktitut'),
    'ik': _('Inupiaq'),
    'ga': _('Irish'),
    'it': _('Italian'),
    'ja': _('Japanese'),
    'jv': _('Javanese'),
    'kl': _('Kalaallisut; Greenlandic'),
    'kn': _('Kannada'),
    'kr': _('Kanuri'),
    'ks': _('Kashmiri'),
    'kk': _('Kazakh'),
    'ki': _('Kikuyu; Gikuyu'),
    'rw': _('Kinyarwanda'),
    'ky': _('Kirghiz; Kyrgyz'),
    'kv': _('Komi'),
    'kg': _('Kongo'),
    'ko': _('Korean'),
    'kj': _('Kuanyama; Kwanyama'),
    'ku': _('Kurdish'),
    'lo': _('Lao'),
    'la': _('Latin'),
    'lv': _('Latvian'),
    'li': _('Limburgan; Limburger; Limburgish'),
    'ln': _('Lingala'),
    'lt': _('Lithuanian'),
    'lu': _('Luba-Katanga'),
    'lb': _('Luxembourgish; Letzeburgesch'),
    'mk': _('Macedonian'),
    'mg': _('Malagasy'),
    'ms': _('Malay'),
    'ml': _('Malayalam'),
    'mt': _('Maltese'),
    'gv': _('Manx'),
    'mi': _('Maori'),
    'mr': _('Marathi'),
    'mh': _('Marshallese'),
    'mn': _('Mongolian'),
    'na': _('Nauru'),
    'nv': _('Navajo; Navaho'),
    'nd': _('Ndebele), North; North Ndebele'),
    'nr': _('Ndebele), South; South Ndebele'),
    'ng': _('Ndonga'),
    'ne': _('Nepali'),
    'se': _('Northern Sami'),
    'no': _('Norwegian'),
    'nn': _('Norwegian Nynorsk; Nynorsk), Norwegian'),
    'oc': _('Occitan (post 1500)'),
    'oj': _('Ojibwa'),
    'or': _('Oriya'),
    'om': _('Oromo'),
    'os': _('Ossetian; Ossetic'),
    'pi': _('Pali'),
    'pa': _('Panjabi; Punjabi'),
    'fa': _('Persian'),
    'pl': _('Polish'),
    'pt': _('Portuguese'),
    'ps': _('Pushto; Pashto'),
    'qu': _('Quechua'),
    'ro': _('Romanian; Moldavian; Moldovan'),
    'rm': _('Romansh'),
    'rn': _('Rundi'),
    'ru': _('Russian'),
    'sm': _('Samoan'),
    'sg': _('Sango'),
    'sa': _('Sanskrit'),
    'sc': _('Sardinian'),
    'sr': _('Serbian'),
    'sn': _('Shona'),
    'ii': _('Sichuan Yi; Nuosu'),
    'sd': _('Sindhi'),
    'si': _('Sinhala; Sinhalese'),
    'sk': _('Slovak'),
    'sl': _('Slovenian'),
    'so': _('Somali'),
    'st': _('Sotho), Southern'),
    'es': _('Spanish; Castilian'),
    'su': _('Sundanese'),
    'sw': _('Swahili'),
    'ss': _('Swati'),
    'sv': _('Swedish'),
    'tl': _('Tagalog'),
    'ty': _('Tahitian'),
    'tg': _('Tajik'),
    'ta': _('Tamil'),
    'tt': _('Tatar'),
    'te': _('Telugu'),
    'th': _('Thai'),
    'bo': _('Tibetan'),
    'ti': _('Tigrinya'),
    'to': _('Tonga (Tonga Islands)'),
    'ts': _('Tsonga'),
    'tn': _('Tswana'),
    'tr': _('Turkish'),
    'tk': _('Turkmen'),
    'tw': _('Twi'),
    'ug': _('Uighur; Uyghur'),
    'uk': _('Ukrainian'),
    'ur': _('Urdu'),
    'uz': _('Uzbek'),
    've': _('Venda'),
    'vi': _('Vietnamese'),
    'vo': _('Volapük'),
    'wa': _('Walloon'),
    'cy': _('Welsh'),
    'fy': _('Western Frisian'),
    'wo': _('Wolof'),
    'xh': _('Xhosa'),
    'yi': _('Yiddish'),
    'yo': _('Yoruba'),
    'za': _('Zhuang; Chuang'),
    'zu': _('Zulu'),
}
