# Generated by Django 4.2.14 on 2024-08-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_rename_experiment_questionseries_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='explainer',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='max_length',
            field=models.IntegerField(default=64),
        ),
        migrations.AddField(
            model_name='question',
            name='max_value',
            field=models.FloatField(default=120),
        ),
        migrations.AddField(
            model_name='question',
            name='min_value',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='min_values',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='profile_scoring_rule',
            field=models.CharField(blank=True, choices=[('LIKERT', 'LIKERT'), ('REVERSE_LIKERT', 'REVERSE_LIKERT'), ('CATEGORIES_TO_LIKERT', 'CATEGORIES_TO_LIKERT')], default='', max_length=128),
        ),
        migrations.AddField(
            model_name='question',
            name='scale_steps',
            field=models.IntegerField(choices=[(5, 5), (7, 7)], default=7),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('', '---------'), ('BooleanQuestion', 'BooleanQuestion'), ('ChoiceQuestion', 'ChoiceQuestion'), ('NumberQuestion', 'NumberQuestion'), ('TextQuestion', 'TextQuestion'), ('LikertQuestion', 'LikertQuestion'), ('LikertQuestionIcon', 'LikertQuestionIcon'), ('AutoCompleteQuestion', 'AutoCompleteQuestion')], default='', max_length=128),
        ),
        migrations.AddField(
            model_name='question',
            name='view',
            field=models.CharField(choices=[('BUTTON_ARRAY', 'BUTTON_ARRAY'), ('CHECKBOXES', 'CHECKBOXES'), ('RADIOS', 'RADIOS'), ('DROPDOWN', 'DROPDOWN')], default='', max_length=128),
        ),
    ]
