# Generated by Django 4.2.14 on 2024-09-12 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_add_custom_question_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choices',
        ),
        migrations.AlterField(
            model_name='question',
            name='key',
            field=models.SlugField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('key', models.SlugField(max_length=128, primary_key=True, serialize=False)),
                ('text', models.TextField(default='')),
                ('index', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
