# Generated by Django 4.2.15 on 2024-09-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_add_question_choice_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='text_en',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='text_nl',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='explainer_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='explainer_nl',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_en',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_nl',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(),
        ),
    ]
