# Generated by Django 4.2.17 on 2025-01-21 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_modeltranslation_populate_zh_hans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioninseries',
            name='index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
