# Generated by Django 4.2.17 on 2025-01-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_provide_default_questioninseries_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
