# Generated by Django 4.2.20 on 2025-09-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_provide_default_choice_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='view',
            field=models.CharField(choices=[('AUTOCOMPLETE', 'Autocomplete'), ('BUTTON_ARRAY', 'Button Array'), ('CHECKBOXES', 'Checkboxes'), ('DROPDOWN', 'Dropdown'), ('ICONRANGE', 'Range slider with icons'), ('RADIOS', 'Radio buttons'), ('RANGE', 'Present a range slider'), ('NUMBER', 'Present a number field'), ('STRING', 'Present a text field'), ('TEXTRANGE', 'Range slider with text')], default='', max_length=16),
        ),
    ]
