# Generated by Django 4.2.24 on 2025-09-30 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiment', '0069_alter_experiment_name_length'),
        ('question', '0009_provide_default_choice_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceList',
            fields=[
                (
                    'key',
                    models.SlugField(max_length=64, primary_key=True, serialize=False),
                ),
                ('from_python', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='editable',
        ),
        migrations.RemoveField(
            model_name='question',
            name='scale_steps',
        ),
        migrations.RemoveField(
            model_name='question',
            name='view',
        ),
        migrations.AddField(
            model_name='question',
            name='from_python',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='question.question',
            ),
        ),
        migrations.AlterField(
            model_name='question',
            name='max_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='max_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='min_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='min_values',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(
                choices=[
                    (
                        'AutoCompleteQuestion',
                        'Autocomplete: Present choices as a dropdown with autocomplete function',
                    ),
                    (
                        'ButtonArrayQuestion',
                        'Button Array: Present choices as a row of buttons',
                    ),
                    (
                        'CheckboxQuestion',
                        'Checkboxes: Present choices as checkboxes (multiple options)',
                    ),
                    (
                        'DropdownQuestion',
                        'Dropdown: Present choices in a dropdown menu',
                    ),
                    (
                        'IconRangeQuestion',
                        'Icon Range: Present choices as a range slider with icons',
                    ),
                    (
                        'NumberQuestion',
                        'Number: Present a number field to select a number',
                    ),
                    ('RadiosQuestion', 'Radios: Present choices as radio buttons'),
                    (
                        'RangeQuestion',
                        'Range: Present a range slider to select a number',
                    ),
                    ('TextQuestion', 'Text: Present a text field to enter free text'),
                    (
                        'TextRangeQuestion',
                        'Text Range: Present choices as a range slider with text',
                    ),
                ],
                default='',
                max_length=32,
            ),
        ),
        migrations.AlterUniqueTogether(
            name='questionseries',
            unique_together={('name', 'block')},
        ),
        migrations.DeleteModel(
            name='QuestionGroup',
        ),
        migrations.AddField(
            model_name='choice',
            name='choicelist',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='choices',
                to='question.choicelist',
            ),
        ),
        migrations.AddField(
            model_name='question',
            name='choices',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='question.choicelist',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('key', 'choicelist')},
        ),
    ]
