# Generated by Django 4.2.17 on 2025-01-21 14:32

from django.db import migrations, models

def choice_to_choice_set(apps, schema_editor):
    ChoiceModel = apps.get_model("question.Choice")
    ChoiceSetModel = apps.get_model("question.ChoiceSet")
    for choice in ChoiceModel.objects.all():
        linked_question = getattr(choice, 'question', None)
        if linked_question:
            cs, has_created_choice_set = ChoiceSetModel.objects.get_or_create(key=f"{linked_question.key}_choices")
            choice.set = cs
            choice.save()
            if has_created_choice_set:
                linked_question.choices = cs
                linked_question.save()

def choice_to_question(apps, schema_editor):
    ChoiceModel = apps.get_model("question.Choice")
    for choice in ChoiceModel.objects.all():
        linked_choice_set = getattr(choice, 'set', None)
        if linked_choice_set:
            choice.question = linked_choice_set.question_set.first()
            choice.save()

class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_introduce_choiceset_and_more'),
    ]

    operations = [
        migrations.RunPython(choice_to_choice_set, reverse_code=choice_to_question),
    ]
