# Generated by Django 4.2.22 on 2025-10-09 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_introduce_choicelist_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_en',
            new_name='text_en',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_nl',
            new_name='text_nl',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_pt',
            new_name='text_pt',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_zh_hans',
            new_name='text_zh_hans',
        ),
    ]
