# Generated by Django 4.2.22 on 2025-10-09 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0013_migrate_choices_to_lists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AlterField(
            model_name='choice',
            name='choicelist',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='choices',
                to='question.choicelist',
            ),
        ),
    ]
