# Generated by Django 4.2.25 on 2025-10-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_remove_choice_question_alter_choice_set'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioninlist',
            options={'ordering': ['index'], 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='questionlist',
            options={'ordering': ['index'], 'verbose_name_plural': 'Question Lists'},
        ),
    ]
