# Generated by Django 4.2.25 on 2026-01-19 14:25

from django.db import migrations, models
import question.models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0015_alter_questioninlist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='color',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Description of color in current theme, e.g. `colorPositive`',
                max_length=32,
                validators=[question.models.validate_color],
            ),
        ),
    ]
