# Generated by Django 6.0.1 on 2026-02-12 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0015_alter_questioninlist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='text_tr',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='explainer_tr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_tr',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
