# Generated by Django 6.0.1 on 2026-03-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0017_choice_question_add_tr_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('AutoCompleteQuestion', 'Autocomplete: Present choices as a dropdown with autocomplete function'), ('ButtonArrayQuestion', 'Button Array: Present choices as a row of buttons'), ('CheckboxQuestion', 'Checkboxes: Present choices as checkboxes (multiple options)'), ('DropdownQuestion', 'Dropdown: Present choices in a dropdown menu'), ('NumberQuestion', 'Number: Present a number field to select a number'), ('RadiosQuestion', 'Radios: Present choices as radio buttons'), ('RangeQuestion', 'Range: Present a range slider to select a number'), ('TextQuestion', 'Text: Present a text field to enter free text'), ('TextRangeQuestion', 'Text Range: Present choices as a range slider with text')], default='', max_length=32),
        ),
    ]
