# Generated by Django 6.0.4 on 2026-04-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0018_remove_icon_range_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='color',
            field=models.CharField(blank=True, choices=[('color_background', 'colorBackground'), ('color_grey', 'colorGrey'), ('color_negative', 'colorNegative'), ('color_neutral1', 'colorNeutral1'), ('color_neutral2', 'colorNeutral2'), ('color_neutral3', 'colorNeutral3'), ('color_positive', 'colorPositive'), ('color_primary', 'colorPrimary'), ('color_secondary', 'colorSecondary'), ('color_text', 'colorText')], default='', help_text='Description of color in current theme, e.g. `colorPositive`', max_length=32),
        ),
    ]
