# Generated by Django 6.0.4 on 2026-04-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0019_restrict_color_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionlist',
            name='index',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
