# Generated by Django 6.0.5 on 2026-05-18 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0020_add_default_questionlist_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioninlist',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_in_list', to='question.question'),
        ),
    ]
