# Generated by Django 6.0.5 on 2026-05-19 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0021_related_name_question_in_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='color',
            field=models.CharField(blank=True, choices=[('colorBackground', 'Background color'), ('colorGrey', 'Grey color'), ('colorNegative', 'Negative color'), ('colorNeutral1', 'Neutral color 1'), ('colorNeutral2', 'Neutral color 2'), ('colorNeutral3', 'Neutral color 3'), ('colorPositive', 'Positive color'), ('colorPrimary', 'Primary color'), ('colorSecondary', 'Secondary color'), ('colorText', 'Text color')], default='', help_text='Description of color in current theme, e.g. `colorPositive`', max_length=32),
        ),
    ]
