# Generated by Django 6.0.5 on 2026-06-01 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0022_alter_choice_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['identifier']},
        ),
        migrations.RenameField(
            model_name='choice',
            old_name='key',
            new_name='identifier',
        ),
        migrations.RenameField(
            model_name='choicelist',
            old_name='key',
            new_name='identifier',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='key',
            new_name='identifier',
        ),
        migrations.AlterUniqueTogether(
            name='choice',
            unique_together={('identifier', 'choicelist')},
        ),
    ]
