# Generated by Django 6.0.5 on 2026-06-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0023_rename_key_as_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='text_de',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='explainer_de',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_de',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
