# Generated by Django 6.0.5 on 2026-07-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0025_add_german_language_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='text_ja',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='explainer_ja',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_ja',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
