# Generated by Django 3.2.18 on 2023-05-23 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='participant_id_url',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
