# Generated by Django 3.2.18 on 2023-04-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='json_data',
            field=models.JSONField(default=dict),
        ),
    ]
