# Generated by Django 3.2.18 on 2023-05-15 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_participant_json_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='json_data',
        ),
        migrations.AddField(
            model_name='participant',
            name='participant_id_url',
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
    ]
