name: Podman check status containers

on:
  push:
  workflow_dispatch:

jobs:
  check-test-status:
    name: Check status of containers on test environment
    environment: test
    runs-on: self-hosted
    steps:
      - name: Check status of containers
        run: podman-compose -f docker-compose-deploy.yml ps


