name: Test suite

on:
  push:

jobs:

  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Backend Tests
        run: sudo docker-compose --env-file .env-github-actions run server bash -c "python manage.py test"

  backend-lint:
    name: Lint Backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo docker-compose --env-file .env-github-actions run server bash -c "flake8"

  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Frontend Tests
        run: sudo docker-compose --env-file .env-github-actions run client yarn test --watchAll=false

  frontend-lint:
    name: Lint Frontend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo docker-compose --env-file .env-github-actions run client yarn lint
