name: Podman build & deploy

on:
  push:
  workflow_dispatch:
  
jobs:
  build:
    environment: test
    runs-on: self-hosted
    env:
      DJANGO_SETTINGS_MODULE: ${{ vars.DJANGO_SETTINGS_MODULE }}
    steps:
      - uses: actions/checkout@v4
      - name: Build Podman images
        run: podman-compose -f docker-compose-deploy.yml build
      - name: Deploy Podman images
        run: podman-compose -f docker-compose-deploy.yml up -d --force-recreate
      - name: Check Podman images
        run: podman-compose -f docker-compose-deploy.yml ps
      - name: Check if DJANGO_SETTINGS_MODULE is set
        run: echo $DJANGO_SETTINGS_MODULE