name: Podman build & deploy

on:
  push:
  workflow_dispatch:
  
jobs:
  build:
    environment: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Build Podman images
        run: podman-compose -f docker-compose-deploy.yml build
      - name: Deploy Podman images
        run: podman-compose -f docker-compose-deploy.yml up -d