name: Podman build & deploy

on:
  push:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build Podman images
        run: podman-compose -f docker-compose-build.yml build
      - name: Deploy Podman images
        run: podman-compose -f docker-compose-build.yml up -d