name: Test suite

on:
  push:
  pull_request:

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Backend Tests
        run: sudo docker-compose --env-file .env-github-actions run server bash -c "python manage.py test"

  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Frontend Tests
        run: sudo docker-compose --env-file .env-github-actions run client yarn test --watchAll=false
