name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "SUCCESS"
      - run: sudo docker-compose run server bash -c "python manage.py test"
